### ISSUE TITLE
Cursor blinking and size

### ISSUE THREAD

**Issue by tom-anders** [sassanh/qnvim#12]
1. The cursor is blinking even in normal mode, is there a way to turn this off?
2. When I zoom with Ctrl+Mouse wheel, the cursor width stays the same instead of adjusting to the current font size.

**Comment by sassanh** [comment]
> 1. The cursor is blinking even in normal mode, is there a way to turn this off?

It doesn't seem to be easy, I can't find an easy way to disable blinking cursor or change its rate. the hard way would be to subclass the text editor and override some internal methods. If you know any easy way please let me know, otherwise lets keep it open for future.

> 2\. When I zoom with Ctrl+Mouse wheel, the cursor width stays the same instead of adjusting to the current font size.

I was able to reproduce it on my machine, I'll try to fix it in the weekend,

**Comment by sassanh** [comment]
@tom-anders the zoom issue among many other issues is resolved in my latest commit on `master` branch. It needs to be tested before being released so I'll try to provide a release next week after I have time to test it, but meanwhile you can clone and build for yourself.

**Comment by tom-anders** [comment]
Cool, I'll have a look!

**Comment by sassanh** [comment]
https://github.com/sassanh/qnvim/releases/tag/v1.2.0

**Comment by Shatur95** [comment]
> It doesn't seem to be easy, I can't find an easy way to disable blinking cursor or change its rate. the hard way would be to subclass the text editor and override some internal methods. If you know any easy way please let me know, otherwise lets keep it open for future.

Maybe set [cursorFlashTime](https://doc.qt.io/qt-5/qapplication.html#cursorFlashTime-prop)?

**Comment by Shatur95** [comment]
> It doesn't seem to be easy, I can't find an easy way to disable blinking cursor or change its rate. the hard way would be to subclass the text editor and override some internal methods. If you know any easy way please let me know, otherwise lets keep it open for future.

I suggest to use [cursorFlashTime](https://doc.qt.io/qt-5/qapplication.html#cursorFlashTime-prop).

**Comment by sassanh** [comment]
> I can send you a PR if you like the proposed solution.

It would be very nice if you could provide a pull request.
