### ISSUE TITLE
qtcreator crash

### ISSUE THREAD

**Issue by beyondsuntong** [sassanh/qnvim#14]
I download the release  (libQNVim-1.2.0-qtcreator-4.9.1-x86_64.so) in my qt-creator plugin directory 
my qt-creator version is official release (see below), I also load this plugin
![Uploading image.png…]()

when I open a file, qt-creator crash
![Uploading image.png…]()

**Comment by beyondsuntong** [comment]
![image](https://user-images.githubusercontent.com/17026320/73742888-6000a200-4788-11ea-818e-e03fed4a3fe5.png)

![image](https://user-images.githubusercontent.com/17026320/73743087-c4236600-4788-11ea-8db2-20271c634fbf.png)

**Comment by sassanh** [comment]
Your Neovim doesn't support api level 6, this plugin uses api level 6. What's the version of your neovim?

**Comment by beyondsuntong** [comment]
NVIM v0.2.2
![image](https://user-images.githubusercontent.com/17026320/73761813-4ff9ba00-47aa-11ea-8146-e58352f00238.png)

**Comment by beyondsuntong** [comment]
![image](https://user-images.githubusercontent.com/17026320/73762067-a36c0800-47aa-11ea-8a17-99d99e72140f.png)

**Comment by sassanh** [comment]
This plugin doesn't work NVIM 0.2.2, please update to latest Neovim.

**Comment by beyondsuntong** [comment]
I updated to latest Neovim, this problem fixed. thanks!
