### ISSUE TITLE
Texteditor.FollowSmybolUnderCursor breaks previous file. 

### ISSUE THREAD

**Issue by tom-anders** [sassanh/qnvim#16]
Say I am in fileA.cpp and use Texteditor.FollowSmybolUnderCursor with the shortcut provided in your example qnvim.vim file. This takes me to fileB.cpp as expected. However, when I go back to fileA.cpp (via QtCreator.GotoPreviousInHistory) the fileA.cpp will appear as empty and I have to restart QtCreator to see its contents again. Let me know if you can reproduce this or need more details.

**Comment by tom-anders** [comment]
This is even clearer if you do FollowSymbolUnderCursorInNextSplit, you will see that the old file suddenly is emptied after the new split appears

**Comment by tom-anders** [comment]
Also, sometimes it works the first time, but then the bug appears everytime after that

**Comment by sassanh** [comment]
Thanks! Unfortunately I'm currently out of time to work on qnvim issues. I expect to work on a Qt project soon and if that happens then I can work on qnvim again.

Meanwhile please feel free to provide pull requests, any help is appreciated.

**Comment by tom-anders** [comment]
Any updates on this?

@Shatur95 I've seen you did some work on this repo recently, have you maybe already looked at this bug?

**Comment by Shatur95** [comment]
@tom-anders, currently I trying to make QtCreator from Neovim instead of making Neovim from QtCreator :D
Nightly versions of Neovim have very fast LSP that can provide similar experience. And for working with CMake as in IDE I made [a plugin](https://github.com/Shatur95/vim-cmake-projects).
But If I will back to QtCreator, I will try to fix.

**Comment by sassanh** [comment]
Unfortunately I'm not working with Qt Creator these days and do not have any time right now, I'm looking forward to see a Qt Creator made from Neovim though :)

**Comment by sassanh** [comment]
@tom-anders Does it always happen for you? I just checked it several times quickly and it didn't happen for me, in case you are using a prebuilt version I suggest building it yourself from latest version, I think some instabilities have been resolved without being released yet.

**Comment by sassanh** [comment]
Closing as no more information is provided.
