### ISSUE TITLE
Can not compile with the latest neovim-qt 

### ISSUE THREAD

**Issue by wdoo02** [sassanh/qnvim#29]
I failed to compile qnvim with the latest neovim-qt, the error is 
```
../qnvimplugin.cpp:95:54: error: invalid use of incomplete type ‘class NeovimQt::InputConv’
 QNVimPlugin::QNVimPlugin(): mInputConv(new NeovimQt::InputConv)

```
The class  NeovimQt::InputConv has been removed from neovim-qt since https://github.com/equalsraf/neovim-qt/commit/548bb1e09aa339571ca4cc8625529fcdc37ceb10

**Comment by sassanh** [comment]
Yeah I think I have seen it and fixed it locally a while ago, seems like I forgot to push, I'll check it in the weekend, thanks for reporting.

**Comment by wdoo02** [comment]
Glad to hear that, thanks in advance.

**Comment by sassanh** [comment]
@wdoo02 I just pushed my changes to master branch, I built this new version a month ago with the latest version of neovim-qt at the time, I hope things haven't changed much by then.

**Comment by wdoo02** [comment]
It's working now, thank you.
