### ISSUE TITLE
Every movement seems to reload the code model (warnings, cppcheck, etc.)

### ISSUE THREAD

**Issue by tom-anders** [sassanh/qnvim#31]
I found that everytime I do _anything_ (even just moving around in normal mode), the code model seems to be reloaded, i.e. cppcheck is run, the warnings turn grey for a short time, etc. Normally, this should only happen when you actually edit anything. Do you have a hint on how this could be fixed? Or is it an inherent problem of the neovim communication?

**Comment by tom-anders** [comment]
This especially kills performance in large files

**Comment by sassanh** [comment]
I think it is possible to avoid many unnecessary code model reloads, I think it probably happened after an update in Qt/QtCreator/Neovim (I guess I resolved such issues in the past)
To do so my plan would be to do not update the QtCreator text when the previous text is the same as the new text.
I wish I could fix it myself but unfortunately currently I'm not using Qt and do not have any time to work on it.

**Comment by sassanh** [comment]
This issue seems to be fixed when I checked it on my machine, let me know if I'm wrong.
