### ISSUE TITLE
Avoid using 7zip for assets in releases

### ISSUE THREAD

**Issue by sassanh** [sassanh/qnvim#41]
We are compressing the plugin assets using 7zip in releases. As far as I know a 7zip unarchiver is not available in macOS or Linux out of the box, so to avoid extra work for users my suggestion is to either not compress the assets at all or compress it using gzip or bzip2 (for macOS and Linux) and zip (for Windows) which are widely used by developers.

Examples of some popular repositories:
Neovim uses gzip and zip: https://github.com/neovim/neovim/releases/tag/stable
Curl uses gzip, bzip2 and zip: https://github.com/curl/curl/releases/tag/curl-7_86_0
Ripgrep uses gzip, bzip2 and zip: https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0
CMake uses gzip: https://github.com/Kitware/CMake/releases
Electron uses zip: https://github.com/electron/electron/releases/tag/v21.3.3

/cc @gikari

**Comment by gikari** [comment]
Unfortunately, we depend on the Qt Creator packaging script, that hardcodes the 7z. 

But, the users won't be needing to unpack the archive by themselves, they just need to select it in the Qt Creator plugin installation dialog. Won't it work without 7z installed?

I didn't encounter any issue installing the package on Linux VM, but it may depend on the distro.

**Comment by sassanh** [comment]
Now I understand 7z is coming from Qt Creator, it is all good then.
