### ISSUE TITLE
$MYVIMRC and $MYQVIMRC point to ~/.config/nvim/init.lua

### ISSUE THREAD

**Issue by j-k-kappes** [sassanh/qnvim#43]
I'm using Qnvim 5.0.2 on Debian GNU/Linux bookworm/sid x86_64.
The nvim keybindings work, but none of the commands from the example qnvim.vim file which I put in ~/.config/nvim/ work. 
When I open $MY(Q)VIMRC both lead to ~/.config/nvim/init.lua.
When I reassign either of them, they reset after I close QtCreator.

**Comment by sassanh** [comment]
Sorry for the late response, you are correct I was able to reproduce it on my machine. It happens when one uses `init.lua` instead of `init.vim`.

It should be fixed in the latest release 10.0.0_1.
