### ISSUE TITLE
How it compares with Qt Creator Vim mode?

### ISSUE THREAD

**Issue by bam80** [sassanh/qnvim#58]
It should be mentioned in the Readme I think.
Also, could clang-tidy, other QQC linters work on top of this plugin's view?

**Comment by sassanh** [comment]
> Also, could clang-tidy, other QQC linters work on top of this plugin's view?

You should disabled formatters that work on `BufWrite` in your Neovim config so that they don't interfere with Qt Creator's formatters/linters.

> It should be mentioned in the Readme I think.

I will add a section to quickly explain it.

**Comment by sassanh** [comment]
I added this section:
https://github.com/sassanh/qnvim#how-does-qnvim-compare-with-qt-creator-vim-mode

**Comment by bam80** [comment]
Many thanks!

To clarify: you wrote about the benefits.
Are there things we sacrifice yet?

**Comment by bam80** [comment]
> You should disabled formatters that work on BufWrite in your Neovim config so that they don't interfere with Qt Creator's formatters/linters.

Could we add copy-pastable instructions to the Readme, as this step would probably be always necessary?

PS:
maybe add that to https://github.com/sassanh/qnvim/blob/master/examples/qnvim.vim?

**Comment by sassanh** [comment]
> To clarify: you wrote about the benefits.
> Are there things we sacrifice yet?

This part: "On the other hand, Qt Creator Vim mode is a built-in feature" is a benefit of Vim Mode I can think of. Probably another temporary advantage of Vim Mode is that it is more stable than qnvim, it is also mentioned in the README.md that qnvim is not very stable and this is not something in the nature of qnvim to be unstable, if more time is spent on developing it, it will eventually becomes stable.

**Comment by sassanh** [comment]
> Could we add copy-pastable instructions to the Readme, as this step would probably be always necessary?

It would make `qnvim.vim` too opinionated. One might keep some of their `BufWrite` autocommands, we should just disable formatters and things that actually edit the buffer. For example if you have a `BufWrite` to copy the file into a backup directory, you don't want it to become disabled.

Btw, I'm not using this plugin at the moment, if I use it and add something for myself that would be beneficial for others, I will definitely commit it in the repository. Also if others who are using this plugin create pull requests, I will help with reviewing and merging the pull requests.

**Comment by bam80** [comment]
> Btw, I'm not using this plugin at the moment

Why not, does the development halted?

**Comment by sassanh** [comment]
I don't work on a Qt project these days, so I don't need to use Qt Creator.
