### ISSUE TITLE
QtCreator 10 build

### ISSUE THREAD

**Issue by bam80** [sassanh/qnvim#59]
Please make a release compatible with QtCreator 10

**Comment by sassanh** [comment]
I'll try to work on merging qtc-6 to the main branch and then it should be much easier to release for newer versions of Qt Creator.
It won't happen very fast, but hopefully not very slow neither. I will update you here.

**Comment by sassanh** [comment]
@bam80 Fortunately it got ready sooner than expected. You can download it from [releases](https://github.com/sassanh/qnvim/releases/tag/v10.0.0).
